

substitutions:
  update_interval: 10s

esphome:
  name: "${name}"
  friendly_name: "${friendly_name}"
  comment: "${device_description} coding by Nguyenho"
  project:
    name: "esphome.deye-inverter"
    version: v1.1.0 (Coding by Nguyenho)
logger:
  level: WARN

api:
  on_client_disconnected:
    - delay: ${safe_mode_delay}
    - if:
        condition:
          not: api.connected
        then:
          - logger.log: "Lost connection to HomeAssistant API - Activating safe mode"
          - script.execute: set_safe_modbus_registers

  on_client_connected:
    - logger.log: "Connection to HomeAssistant API restored"
ota:
  - platform: esphome
wifi:
  ssid: ${wifi_ssid}
  password: ${wifi_password}

  ap:
    ssid: "${friendly_name} Fallback Hotspot"
captive_portal:
button:
  - platform: restart
    icon: mdi:restart
    name: "Restart"
    entity_category: "diagnostic"  
    id: rst              
text_sensor:
  - platform: wifi_info
    ip_address:
      name: "IP"
      icon: mdi:ip-network-outline 
    ssid:
      name: SSID     
sensor:
  - platform: wifi_signal 
    name: "RSSI"
    id: wifi_signal_db
    entity_category: "diagnostic"         

binary_sensor:
  - platform: status
    name: "Status"
    entity_category: "diagnostic"
uart:
  id: modbus_uart
  baud_rate: ${baud_rate}
  stop_bits: 1

modbus:
  id: modbus_1
  uart_id: modbus_uart

modbus_controller:
  - id: ${modbus_controller_id}
    address: ${modbus_inverter_address}
    modbus_id: modbus_1
    setup_priority: -10
    update_interval: ${update_interval}
    command_throttle: 150ms
    offline_skip_updates: 3








