

substitutions:
  update_interval: 6s

esphome:
  name: "${name}"
  friendly_name: "${friendly_name}"
  comment: "${device_description} coding by Nguyenho"
  project:
    name: "esphome.deye-inverter"
    version: "0.10.0"

logger:
  level: WARN

api:
  on_client_disconnected:
    - delay: ${safe_mode_delay}
    - if:
        condition:
          not: api.connected
        then:
          - logger.log: "Lost connection to HomeAssistant API - Activating safe mode"
          - script.execute: set_safe_modbus_registers

  on_client_connected:
    - logger.log: "Connection to HomeAssistant API restored"
ota:
  - platform: esphome
wifi:
  ssid: ${wifi_ssid}
  password: ${wifi_password}

  ap:
    ssid: "${friendly_name} Fallback Hotspot"
captive_portal:

uart:
  id: modbus_uart
  baud_rate: ${baud_rate}
  stop_bits: 1

modbus:
  id: modbus_1
  uart_id: modbus_uart

modbus_controller:
  - id: ${modbus_controller_id}
    address: ${modbus_inverter_address}
    modbus_id: modbus_1
    setup_priority: -10
    update_interval: ${update_interval}
    command_throttle: 60ms
    offline_skip_updates: 3


